name:                 v1
version:              0.1.0.0
visibility:           public
id:                   v1-0.1.0.0-1cVKa1UikutFXyCOzQIOiH
key:                  v1-0.1.0.0-1cVKa1UikutFXyCOzQIOiH
abi:                  facb135de8a2ef2397e1a6bd8673327d
exposed:              True
exposed-modules:      Gcds Queue
hidden-modules:       Paths_v1
import-dirs:
    /Users/brandoncho/Downloads/coding/CMPT383/vitamins/v1/.stack-work/install/aarch64-osx/cb0e72626d8bc8d81775cb0932c6b8451850b9ae3f581ae69bbc147e5a4126d2/9.0.2/lib/aarch64-osx-ghc-9.0.2/v1-0.1.0.0-1cVKa1UikutFXyCOzQIOiH

library-dirs:
    /Users/brandoncho/Downloads/coding/CMPT383/vitamins/v1/.stack-work/install/aarch64-osx/cb0e72626d8bc8d81775cb0932c6b8451850b9ae3f581ae69bbc147e5a4126d2/9.0.2/lib/aarch64-osx-ghc-9.0.2/v1-0.1.0.0-1cVKa1UikutFXyCOzQIOiH

dynamic-library-dirs:
    /Users/brandoncho/Downloads/coding/CMPT383/vitamins/v1/.stack-work/install/aarch64-osx/cb0e72626d8bc8d81775cb0932c6b8451850b9ae3f581ae69bbc147e5a4126d2/9.0.2/lib/aarch64-osx-ghc-9.0.2

data-dir:
    /Users/brandoncho/Downloads/coding/CMPT383/vitamins/v1/.stack-work/install/aarch64-osx/cb0e72626d8bc8d81775cb0932c6b8451850b9ae3f581ae69bbc147e5a4126d2/9.0.2/share/aarch64-osx-ghc-9.0.2/v1-0.1.0.0

hs-libraries:         HSv1-0.1.0.0-1cVKa1UikutFXyCOzQIOiH
depends:              base-4.15.1.0
haddock-interfaces:
    /Users/brandoncho/Downloads/coding/CMPT383/vitamins/v1/.stack-work/install/aarch64-osx/cb0e72626d8bc8d81775cb0932c6b8451850b9ae3f581ae69bbc147e5a4126d2/9.0.2/doc/v1-0.1.0.0/v1.haddock

haddock-html:
    /Users/brandoncho/Downloads/coding/CMPT383/vitamins/v1/.stack-work/install/aarch64-osx/cb0e72626d8bc8d81775cb0932c6b8451850b9ae3f581ae69bbc147e5a4126d2/9.0.2/doc/v1-0.1.0.0
